name: 'secret-scanning-custom-action'
description: 'Testing Suite for GitHub Secret Scanning Custom Patterns'
branding:
  icon: shield
  color: blue

inputs:
  repository:
    description: Repository owner and repo name
    default: ${{ github.repository }}
  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}
  mode:
    description: Secret Scanning Test Suite Mode
    default: validate
  templates-path:
    description: Path to template directory
  template-main:
    description: Main README template name
  template-patterns:
    description: PATTERNS template name
  path:
    description: Path to scan
    default: ${{ github.workspace }}
  argvs:
    description: Additional arguments

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: '3.9'
      if: runner.environment == 'github-hosted' || (runner.tool_cache != '' && runner.tool_cache != null)

    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::Installing Dependencies"
        pushd ${{ github.action_path }}
        python3 -m pip install pipenv && pipenv install
        popd
        echo "::endgroup::"

    - name: Run Secret Scanning tools
      shell: bash
      env:
        INPUTS_MODE: ${{ inputs.mode }}
        INPUTS_PATH: ${{ inputs.path }}
        INPUTS_TOKEN: ${{ inputs.token }}
        INPUTS_REPOSITORY: ${{ inputs.repository }}
        INPUTS_TEMPLATES_PATH: ${{ inputs.templates-path }}
        INPUTS_TEMPLATE_MAIN: ${{ inputs.template-main }}
        INPUTS_TEMPLATE_PATTERNS: ${{ inputs.template-patterns }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}
      run: |
        echo "::group::Running Secret Scanning tools: ${INPUTS_MODE}"

        cd "$GITHUB_ACTION_PATH"
        pipenv run python3 -m secretscanning \
          "--${INPUTS_MODE}" \
          --path "${INPUTS_PATH}" \
          --github-token "${INPUTS_TOKEN}" \
          --github-repository "${INPUTS_REPOSITORY}" \
          ${INPUTS_TEMPLATES_PATH:+--templates "${INPUTS_TEMPLATES_PATH}"} \
          ${INPUTS_TEMPLATE_MAIN:+--templates-main "${INPUTS_TEMPLATE_MAIN}"} \
          ${INPUTS_TEMPLATE_PATTERNS:+--templates-patterns "${INPUTS_TEMPLATE_PATTERNS}"}
          ${{ inputs.argvs }}
