name: 'secret-scanning-custom-action'
description: 'Testing Suite for GitHub Secret Scanning Custom Patterns'

inputs:
  repository:
    description: Repository owner and repo name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}

  mode:
    description: Secret Scanning Test Suite Mode
    default: validate

  template-main:
    description: Main README Template
    default: ${{ github.action_path }}/templates/README.md
  
  template-patterns:
    description: Main Pattern Template
    default: ${{ github.action_path }}/templates/PATTERNS.md

  argvs:
    description: 'Additional Arguments'


runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - shell: bash
      run: |
        echo "::group::Installing Dependencies"
        pushd ${{ github.action_path }}
        python3 -m pip install pipenv && python3 -m pipenv install --system
        popd
        echo "::endgroup::"
    - shell: bash
      env:
        INPUTS_MODE: ${{ inputs.mode }}
        INPUTS_TOKEN: ${{ inputs.token }}
        INPUTS_REPOSITORY: ${{ inputs.repository }}
        INPUTS_TEMPLATE_MAIN: ${{ inputs.template-main }}
        INPUTS_TEMPLATE_PATTERNS: ${{ inputs.template-patterns }}
      run: |
        PYTHONPATH=${{ github.action_path }} && export PYTHONPATH=${{ github.action_path }}
        python3 -m secretscanning \
          "--${INPUTS_MODE}" \
          --github-token "${INPUTS_TOKEN}" \
          --github-repository "${INPUTS_REPOSITORY}" \
          --templates-main "${INPUTS_TEMPLATE_MAIN}" \
          --templates-patterns "${INPUTS_TEMPLATE_PATTERNS}" \
          ${{ inputs.argvs }}
