
name: Configuration Secrets

patterns:
  - name: Django Secret Key
    type: django_secret_key
    regex:
      version: 0.1
      pattern: |
        [^\s"'(${{)][^\r\n'"]*
      start: |
        (?:\A|[^0-9A-Za-z])SECRET_KEY\s*=\s*["']?
      end: |
        \z|[\r\n'"]
    test:
      data: SECRET_KEY=1fsjdgvbdsjfksdgfjslfhwuefldhsfksdfhj
      start_offset: 11
      end_offset: -1
