
name: Configuration Secrets

patterns:
  - name: Django Secret Key
    type: django_secret_key
    regex:
      version: 0.1
      pattern: |
        [^\s"'(${{)][^\r\n'"]*
      start: |
        (?:\A|[^0-9A-Za-z])SECRET_KEY\s*=\s*["']?
      end: |
        \z|[\r\n'"]
      additional_not_match:
        - ^TEST$
    comments:
      - |
        Django secret key is used to provide cryptographic signing, and should be kept secret.
        See: https://docs.djangoproject.com/en/1.11/ref/settings/#secret-key
    test:
      data: SECRET_KEY=1fsjdgvbdsjfksdgfjslfhwuefldhsfksdfhj
      start_offset: 11
      end_offset: -1
    expected:
      - name: django_key.txt
        start_offset: 11
        end_offset: 47
      - name: django_key.txt
        start_offset: 49
        end_offset: 96
