name: Run on examples

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Get token
        id: get_workflow_token
        if: github.actor != 'dependabot[bot]'
        uses: peter-murray/workflow-application-token-action@13145a6fb7bf0a37567dce5aed1447d3d3a007bc # v4.0.1
        with:
          application_id: ${{ secrets.ADVANCED_SECURITY_APP_ID }}
          application_private_key: ${{ secrets.ADVANCED_SECURITY_APP_KEY }}

      - name: Install dependencies
        run: python3 -m pip install pipenv && python3 -m pipenv install

      # Run Validation
      - name: Run - full example
        if: github.actor != 'dependabot[bot]'
        env:
          GITHUB_REPOSITORY: advanced-security/secret-scanning-custom-patterns
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          pipenv run snapshot -p ./examples/
          pipenv run validate -p ./examples/
          pipenv run markdown -p ./examples/ --cwd ./examples/
