name: Self test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  run:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Get Token
        id: get_workflow_token
        if: github.actor != 'dependabot[bot]'
        uses: peter-murray/workflow-application-token-action@13145a6fb7bf0a37567dce5aed1447d3d3a007bc #v3.0.0
        with:
          application_id: ${{ secrets.ADVANCED_SECURITY_APP_ID }}
          application_private_key: ${{ secrets.ADVANCED_SECURITY_APP_KEY }}

      - name: Run - self test - validate
        if: github.actor != 'dependabot[bot]'
        uses: ./
        with:
          mode: validate
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Run - self test - markdown
        if: github.actor != 'dependabot[bot]'
        uses: ./
        with:
          mode: markdown
          token: ${{ steps.get_workflow_token.outputs.token }}
  
